[caller_settings]
config_name = "dna_r9.4.1_450bps_hac"
host = "127.0.0.1"
port = 5555

[conditions]
reference = "integration/readfish/data/covid_natural_index.mmi"

[conditions.0]
name = "select_covid"
control = false
min_chunks = 0
max_chunks = 3
targets = ["NC_045512.2"]
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"